# This workflow will lint all files in repo using Pylint.

name: Pylint

on: push

jobs:
  pylint:
    name: pythonLinter
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv venv_test
        source venv_test/bin/activate
        python -m pip install pylint
        if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
    - name: Analysing the code with Pylint
      run: |
        source venv_test/bin/activate
        pylint $(git ls-files '*.py')
  eslint:
    name: jsLinter
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.0"
          cache: "npm"
 
      - name: Install npm@9.6.6
        run: npm i -g npm@9.6.6
 
      - name: Install dependencies
        id: install-dependencies
        run: npm ci --prefer-offline
 
      - name: Lint
        run: npm run lint
